name = "Ion "
license = "MIT"
licenselink = "https://github.com/dakeouo/ion-hugo-theme/blob/main/LICENSE"
description = "A free responsive templated by TEMPLATED"

homepage = "https://github.com/dakeouo/ion-hugo-theme"

tags = ["Blog","Clean","html5","Responsive","Minimal"]
features = ["posts", "responsive", "google analytics"]
min_version = 0.82.0

[author]
  name = "Dake Hong"
  homepage = "https://github.com/dakeouo"

[original]
  name = "templated"
  homepage = "https://templated.co/"